export const animalsData = [
  { type: "turtle", icon: "🐢", active: false },
  { type: "lion", icon: "🦁", active: false },
  { type: "elephant", icon: "🐘", active: false },
  { type: "giraffe", icon: "🦒", active: false },
  { type: "penguin", icon: "🐧", active: false },
  { type: "dolphin", icon: "🐬", active: false },
  { type: "koala", icon: "🐨", active: false },
  { type: "panda", icon: "🐼", active: false },
  { type: "octopus", icon: "🐙", active: false },
  { type: "tiger", icon: "🐅", active: false },
  { type: "zebra", icon: "🦓", active: false },
  { type: "kangaroo", icon: "🦘", active: false },
  { type: "owl", icon: "🦉", active: false },
  { type: "snake", icon: "🐍", active: false },
  { type: "bear", icon: "🐻", active: false },
  { type: "crocodile", icon: "🐊", active: false },
  { type: "whale", icon: "🐋", active: false },
  { type: "shark", icon: "🦈", active: false },
  { type: "peacock", icon: "🦚", active: false },
];
