export const animalsData = [
  { type: "turtle", icon: "🐢" },
  { type: "lion", icon: "🦁" },
  { type: "elephant", icon: "🐘" },
  { type: "giraffe", icon: "🦒" },
  { type: "penguin", icon: "🐧" },
  { type: "dolphin", icon: "🐬" },
  { type: "koala", icon: "🐨" },
  { type: "panda", icon: "🐼" },
  { type: "octopus", icon: "🐙" },
  { type: "tiger", icon: "🐅" },
  { type: "zebra", icon: "🦓" },
  { type: "kangaroo", icon: "🦘" },
  { type: "owl", icon: "🦉" },
  { type: "snake", icon: "🐍" },
  { type: "bear", icon: "🐻" },
  { type: "crocodile", icon: "🐊" },
  { type: "whale", icon: "🐋" },
  { type: "shark", icon: "🦈" },
  { type: "peacock", icon: "🦚" },
];
